## postgres 9.5 setup adapted from: https://github.com/travis-ci/travis-ci/issues/4264

sudo: false
dist: trusty
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - bundle exec rake --trace db:setup
script:
  - bundle exec rspec --format progress --tag ~type:acceptance
branches:
  only:
    - master
language: ruby
rvm:
  - "2.3.1"
cache: bundler
bundler_args: --without production --retry=6
