# PostgreSQL 9.5 setup adapted from: https://github.com/travis-ci/travis-ci/issues/4264
branches:
  only:
    - master
sudo: false
dist: trusty
language: ruby
rvm: 2.3.7
addons:
  postgresql: 9.6
cache: bundler
bundler_args: --without production --retry=6
before_script:
  - bundle exec rake --trace db:setup
script:
  - bundle exec rspec --format progress --tag ~type:acceptance
